# Experiment Setup

title: "Experiment_2"
description: "Foo Bar"
regions:
  - name: "dining_room"
    min_x: 4.5
    max_x: 8.5
    min_y: 0.5
    max_y: 3.5
    min_z: 0
    max_z: 1.5
  - name: "kitchen"
    min_x: 6.5
    max_x: 9.0
    min_y: -5.0
    max_y: 0.0
    min_z: 0.0
    max_z: 1.5
  - name: "bedroom"
    min_x: -9.0
    max_x: -3.0
    min_y: -1.0
    max_y: 2.4
    min_z: 0
    max_z: 1.5
  - name: "living_room"
    min_x: -2.0
    max_x: 2.0
    min_y: -4.0
    max_y: 0.0
    min_z: 0.0
    max_z: 1.5
objects:
  - name: "cup"
    priors:
      - name: kitchen
        weight: 0.5
      - name: bedroom
        weight: 0.5
  - name: "spoon"
    priors:
      - name: kitchen
        weight: 0.5
      - name: dining_room
        weight: 0.5
observations:
  - name: "cup"
    x: 8.0
    y: -2.5
    z: 0.8
frames:
  - "grasp_cup"
  - "grasp_spoon"
  - "stir_cup"
steps:
  - "Update Filters"
  - "Execute stir_cup"
  - "Observe"
  - "Update Filters"
  - "Execute stir_cup"
  # - "Observe"

