# Experiment Setup

title: "iros23_makeCoffee"
description: ""
regions:
  - name: "cafe"
    points:
      - 53.531, 15.509, 0
      - 55.864, 18.202, 0
      - 54.378, 19.064, 0
      - 52.190, 16.383, 0
      - 53.531, 15.509, 1.5
      - 55.864, 18.202, 1.5
      - 54.378, 19.064, 1.5
      - 52.190, 16.383, 1.5

  # - name: "kitchenette_map"
  #   points:
  #     - 3.592, 0.648, 0
  #     - -10.927, -12.763, 0
  #     - -32.216, 6.620, 0
  #     - -17.680, 21.880, 0
  #     - 3.592, 0.648, 1.5
  #     - -10.927, -12.763, 1.5
  #     - -32.216, 6.620, 1.5
  #     - -17.680, 21.880, 1.5
  - name: "map"
    points:
      - 44.685, -0.326, 0
      - 58.729, 17.124, 0
      - 43.028, 24.631, 0
      - 32.727, 9.942, 0
      - 44.685, -0.326, 1.5
      - 58.729, 17.124, 1.5
      - 43.028, 24.631, 1.5
      - 32.727, 9.942, 1.5
  - name: "cameron_table"
    points:
      - -1.029, 5.490, 0
      - -1.554, 6.186, 0
      - -2.674, 4.945, 0
      - -2.137, 4.497, 0
      - -1.029, 5.490, 1.5
      - -1.554, 6.186, 1.5
      - -2.674, 4.945, 1.5
      - -2.137, 4.497, 1.5
  - name: "kitchenette"
    points:
      - -23.998, 11.246, 0
      - -23.133, 10.623, 0
      - -25.028, 8.637, 0
      - -25.607, 9.618, 0
      - -23.998, 11.246, 1.5
      - -23.133, 10.623, 1.5
      - -25.028, 8.637, 1.5
      - -25.607, 9.618, 1.5

objects:
  - name: "mug"
    priors:
      - name: "cafe"
        weight: 0.5
  # - name: "master_chef_can"
  #   priors:
  #     - name: "collab"
  #       weight: 1.0 
  # - name: "bar_table"
  #   priors:
  #     - name: "bar_table"
  #       weight: 1.0       
  # - name: "mustard_bottle"
  #   priors:
  #     - name: "lab"
  #       weight: 1.0
frames:
  # - "grasp_master_chef_can"
  # - "grasp_cracker_box"
  # - "put_cracker_box_on_bar_table"
  # - "grasp_mustard_bottle"
  # - "grasp_sugar_box"
  # - "grasp_soup"
  - "grasp_mug"
  # - "make_coffee"
  # - "pour_coffee_mug"
  # - "make_coffee"
  #- "grasp_cup"
  #- "grasp_spoon"
  # - "pour_bowl"
  # - "stir_bowl"
  #- "stir_cup"
# observations:
#   - name: "spoon"
#     x: 6.5
#     y: 2
#     z: 0.7
#   - name: "cup"
#     x: 7
#     y: -3
#     z: 0.8
  # - name: "bowl"
  #   x: 8
  #   y: -1
  #   z: 0.8
action_history:
  - "idle"
