# Experiment Setup

title: "make_cereal_bowl_video"
description: ""
regions:
  # - name: "map"
  #   points:
  #     - -5.414, -0.266, 0
  #     - 2.066, -0.266, 0
  #     - 2.066, 18.879, 0
  #     - -6.005, 18.879, 0
  #     - -5.414, -0.266, 1.5
  #     - 2.066, -0.177, 1.5
  #     - 2.066, 18.879, 1.5
  #     - -6.005, 18.879, 1.5
  - name: "map"
    points:
      - -0.955, -1.864, 0.0
      - 2.113, -1.799, 0.0
      - 1.658, 12.665, 0.0
      - -0.971, 12.659, 0.0
      - -0.955, -1.864, 1.5
      - 2.113, -1.799, 1.5
      - 1.658, 12.665, 1.5
      - -0.971, 12.659, 1.5
  
  # - name: "lab"
  #   points:
  #     - -5.414, -0.266, 0
  #     - 2.066, -0.266, 0
  #     - 2.066, 12.347, 0
  #     - -6.005, 12.347, 0
  #     - -5.414, -0.266, 1.5
  #     - 2.066, -0.266, 1.5
  #     - 2.066, 12.347, 1.5
  #     - -6.005, 12.347, 1.5

  - name: "lab"
    points:
      - -0.955, -1.864, 0.0
      - 2.113, -1.799, 0.0
      - 1.658, 12.665, 0.0
      - -0.971, 12.659, 0.0
      - -0.955, -1.864, 1.5
      - 2.113, -1.799, 1.5
      - 1.658, 12.665, 1.5
      - -0.971, 12.659, 1.5

  # - name: "collab"
  #   points:
  #     - -5.106, 15.252, 0
  #     - 0.354, 15.252, 0
  #     - 0.354, 18.520, 0
  #     - -5.106, 18.520, 0
  #     - -5.106, 15.252, 1.5
  #     - 0.354, 15.252, 1.5
  #     - 0.354, 18.520, 1.5
  #     - -5.106, 18.520, 1.5
  # - name: "cafe"
  #   points:
  #     - 53.531, 15.509, 0
  #     - 55.864, 18.202, 0
  #     - 54.378, 19.064, 0
  #     - 52.190, 16.383, 0
  #     - 53.531, 15.509, 1.5
  #     - 55.864, 18.202, 1.5
  #     - 54.378, 19.064, 1.5
  #     - 52.190, 16.383, 1.5

  # - name: "kitchenette_map"
  #   points:
  #     - 3.592, 0.648, 0
  #     - -10.927, -12.763, 0
  #     - -32.216, 6.620, 0
  #     - -17.680, 21.880, 0
  #     - 3.592, 0.648, 1.5
  #     - -10.927, -12.763, 1.5
  #     - -32.216, 6.620, 1.5
  #     - -17.680, 21.880, 1.5

objects:
  - name: "bowl"
    priors:
      - name: "lab"
        weight: 1

  - name: "cracker_box"
    priors:
      - name: "lab"
        weight: 1      
  # - name: "master_chef_can"
  #   priors:
  #     - name: "collab"
  #       weight: 1.0 
  # - name: "bar_table"
  #   priors:
  #     - name: "bar_table"
  #       weight: 1.0       
  # - name: "mustard_bottle"
  #   priors:
  #     - name: "lab"
  #       weight: 1.0
frames:
  - "grasp_cracker_box"
  - "pour_cereal_bowl"
  # - "grasp_master_chef_can"
  # - "put_cracker_box_on_bar_table"
  # - "grasp_mustard_bottle"
  # - "grasp_sugar_box"
  # - "grasp_soup"
  # - "grasp_mug"
  # - "make_coffee"
  # - "pour_coffee_mug"
  # - "make_coffee"
  #- "grasp_cup"
  #- "grasp_spoon"
  # - "stir_bowl"
  #- "stir_cup"
# observations:
#   - name: "spoon"
#     x: 6.5
#     y: 2
#     z: 0.7
#   - name: "cup"
#     x: 7
#     y: -3
#     z: 0.8
# - name: "bowl"
#   x: 8
#   y: -1
#   z: 0.8
action_history:
  - "idle"
